apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dynamic-pv-scaler.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dynamic-pv-scaler.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
{{- range $key, $value := .Values.configMaps }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
