apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
    name: {{ .Values.name }}-config
    app: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.configMaps }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
