---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.imageName }}:{{ .Values.imageTag }}
        imagePullPolicy: Always 
        env:
        - name: PROMETHEUS_URL 
          value: {{ .Values.prometheusUrl }}
        - name: CONFIG_FILE 
          value: {{ .Values.configFileLocation }}
        volumeMounts:
          - mountPath: {{ .Values.configFileLocation }}
            name: {{ .Values.name }}-config
            subPath: config.yaml
      volumes:
        - name: {{ .Values.name }}-config
          configMap:
            name: {{ .Values.name }}-config
      serviceAccount: {{ .Values.name }}
      serviceAccountName: {{ .Values.name }}
