---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dynamic-pv-scaler.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dynamic-pv-scaler.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dynamic-pv-scaler.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dynamic-pv-scaler.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "dynamic-pv-scaler.fullname" . }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }} 
        env:
        - name: PROMETHEUS_URL 
          value: {{ .Values.prometheus.url }}
        - name: CONFIG_FILE 
          value: "/etc/opstree.conf.d/config.yaml"
        volumeMounts:
          - mountPath: /etc/opstree.conf.d/config.yaml
            name: {{ include "dynamic-pv-scaler.fullname" . }}-config
            subPath: config.yaml
      volumes:
        - name: {{ include "dynamic-pv-scaler.fullname" . }}-config
          configMap:
            name: {{ include "dynamic-pv-scaler.fullname" . }}-config
{{- if .Values.serviceAccount.create }}
      serviceAccount: {{ include "dynamic-pv-scaler.fullname" . }}
      serviceAccountName: {{ include "dynamic-pv-scaler.fullname" . }}
{{- end }}
