---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dynamic-pv-scaler.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dynamic-pv-scaler.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaim"]
  verbs: ["get", "watch", "list", "delete", "create", "update"]
