---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaim"]
  verbs: ["get", "watch", "list", "delete", "create", "update"]
