---
name: dynamic-pv-scaler
namespace: dynamic-pv-scaler
imageName: quay.io/opstree/dynamic-pv-scaler
imageTag: latest
prometheusUrl: http://prometheus.opstree.com
configFileLocation: /etc/ot-conf.d/config.yaml
configMaps:
  config.yaml: |
    ---
    - namespace: test123
      scale_percentage: 50
      threshold_percentage: 80
      pvc_name: data-mysql-0
