---
image:
  name: quay.io/opstree/dynamic-pv-scaler
  tag: latest
  imagePullPolicy: IfNotPresent

prometheus:
  url: http://prometheus.opstree.com

configMaps:
  config.yaml: |
    ---
    - namespace: test123
      scale_percentage: 50
      threshold_percentage: 80
      pvc_name: data-mysql-0

serviceAccount:
  create: true
